version: '3'

vars:
    TARGET_FOLDER: build

    SOURCE_FOLDER:
        sh: find . -regex ".*\.go$" | head -n 1 | grep -Po ".*(?=\/)"

    AUTHOR:
        sh: grep -Po "(?<=name\s=\s).*" ~/.gitconfig

    APP_NAME:
        sh: pwd | tr '/' '\n' | tail -1

    ARCH:
        sh: arch

    DATE:
        sh: date

    GIT_COMMIT_NO:
        sh: git rev-list --all --count

    GIT_COMMIT_HASH:
        sh: git rev-parse HEAD

tasks:
    default:
        desc: default task, test and build
        cmds:
            - task: test
            - task: build

    build:
        desc: build using simple 'go build'
        cmds:
            - cmd: mkdir -p $(pwd)/{{.TARGET_FOLDER}}
            - cmd: >-
                CGO_ENABLED=0
                go build -o $(pwd)/{{.TARGET_FOLDER}}/{{.APP_NAME}}
                -ldflags "-s -w -X 'main.BUILDTAGS={
                _subversion: {{.GIT_COMMIT_NO}}, Author: {{.AUTHOR}},
                Build date: {{.DATE}}, Git hash: {{.GIT_COMMIT_HASH}}
                }'"
                src/*.go
            - cmd: file $(pwd)/build/fprint
    test:
        desc: run tests
        cmds:
            - cmd: go test -cover -bench=. {{.SOURCE_FOLDER}}/*.go

    xbuild:
        desc: extended build utilising my personal build script 'bob'
        cmds:
            - cmd: >-
                bob -b V -c
                -f '_subversion: {{.GIT_COMMIT_NO}}, Author: {{.AUTHOR}},
                Build date: {{.DATE}}, Git hash: {{.GIT_COMMIT_HASH}}'
